name: CI/CD Pipeline for Mule App

on:
  push:
    branches:
      - dev
      - uat
      - main
      - feature/test*

permissions:
  contents: write

env:
  CONNECTED_APP_CLIENT_ID: ${{ secrets.CONNECTED_APP_CLIENT_ID }}
  CONNECTED_APP_CLIENT_SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
  GROUP_ID: ${{ secrets.GROUPID }}

jobs:
  Publish_to_Exchange:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Publish to Exchange
        run: |
          mvn clean deploy --settings .maven/settings.xml -DskipTests \
            -Dclient.id=${CONNECTED_APP_CLIENT_ID} \
            -Dclient.secret=${CONNECTED_APP_CLIENT_SECRET} \
            -Danypoint.platform.client_id=${CONNECTED_APP_CLIENT_ID} \
            -Danypoint.platform.client_secret=${CONNECTED_APP_CLIENT_SECRET} \
            -DgroupId=${GROUP_ID}

  Deploy_to_DEV:
    needs: Publish_to_Exchange
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Deploy to DEV
        run: |
          mvn deploy --settings .maven/settings.xml -DskipTests -DmuleDeploy \
            -Dclient.id=${CONNECTED_APP_CLIENT_ID} \
            -Dclient.secret=${CONNECTED_APP_CLIENT_SECRET} \
            -Danypoint.platform.client_id=${CONNECTED_APP_CLIENT_ID} \
            -Danypoint.platform.client_secret=${CONNECTED_APP_CLIENT_SECRET} \
            -DgroupId=${GROUP_ID} \
            -Denv=dev

  Deploy_to_UAT:
    needs: Publish_to_Exchange
    if: github.ref == 'refs/heads/uat'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Deploy to UAT
        run: |
          mvn deploy --settings .maven/settings.xml -DskipTests -DmuleDeploy \
            -Dclient.id=${CONNECTED_APP_CLIENT_ID} \
            -Dclient.secret=${CONNECTED_APP_CLIENT_SECRET} \
            -Danypoint.platform.client_id=${CONNECTED_APP_CLIENT_ID} \
            -Danypoint.platform.client_secret=${CONNECTED_APP_CLIENT_SECRET} \
            -DgroupId=${GROUP_ID} \
            -Denv=uat

  Deploy_to_PROD:
    needs: Publish_to_Exchange
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Deploy to PROD
        run: |
          mvn deploy --settings .maven/settings.xml -DskipTests -DmuleDeploy \
            -Dclient.id=${CONNECTED_APP_CLIENT_ID} \
            -Dclient.secret=${CONNECTED_APP_CLIENT_SECRET} \
            -Danypoint.platform.client_id=${CONNECTED_APP_CLIENT_ID} \
            -Danypoint.platform.client_secret=${CONNECTED_APP_CLIENT_SECRET} \
            -DgroupId=${GROUP_ID} \
            -Denv=prod
