name: Publish and Deploy Pipeline

on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - dev
      - uat
      - main
      - feature/*

jobs:
  feature-or-dev:
    if: startsWith(github.ref_name, 'feature/') || github.ref_name == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17

      - name: Build and Deploy
        run: |
          echo "Deploying to DEV for branch $GITHUB_REF_NAME"
          mvn clean deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
          -Dclient.id="${{ secrets.DEV_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.DEV_CLIENT_SECRET }}" \
          -Danypoint.platform.client_id="${{ secrets.DEV_PLATFORM_CLIENT_ID }}" \
          -Danypoint.platform.client_secret="${{ secrets.DEV_PLATFORM_CLIENT_SECRET }}"

  uat:
    if: github.event.pull_request.merged == true && github.ref_name == 'uat'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17

      - name: Deploy to UAT
        run: |
          echo "Deploying to UAT for branch $GITHUB_REF_NAME"
          mvn deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
          -Dclient.id="${{ secrets.UAT_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.UAT_CLIENT_SECRET }}" \
          -Danypoint.platform.client_id="${{ secrets.UAT_PLATFORM_CLIENT_ID }}" \
          -Danypoint.platform.client_secret="${{ secrets.UAT_PLATFORM_CLIENT_SECRET }}"

  prod:
    if: github.event.pull_request.merged == true && github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17

      - name: Deploy to PROD
        run: |
          echo "Deploying to PROD for branch $GITHUB_REF_NAME"
          mvn deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
          -Dclient.id="${{ secrets.PROD_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.PROD_CLIENT_SECRET }}" \
          -Danypoint.platform.client_id="${{ secrets.PROD_PLATFORM_CLIENT_ID }}" \
          -Danypoint.platform.client_secret="${{ secrets.PROD_PLATFORM_CLIENT_SECRET }}"
