name: CI/CD for MuleSoft Application

on:
  push:
    branches:
      - dev
      - uat
      - main
      - feature/test*

permissions:
  contents: write

jobs:
  publish-to-exchange:
    name: Publish to Exchange
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Publish to Exchange
        run: |
          mvn clean deploy -DskipTests --settings .maven/settings.xml \
            -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
            -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
            -Danypoint.platform.client_id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
            -Danypoint.platform.client_secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"

  deploy-to-dev:
    name: Deploy to DEV
    needs: publish-to-exchange
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Deploy to CloudHub2 - DEV
        run: |
          mvn deploy -DskipTests -DmuleDeploy --settings .maven/settings.xml \
            -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
            -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
            -Danypoint.platform.client_id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
            -Danypoint.platform.client_secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
            -DcloudhubEnvironment=dev \
            -Dtarget=DEV_TARGET \
            -Denv=dev

  deploy-to-uat:
    name: Deploy to UAT
    needs: publish-to-exchange
    if: github.ref == 'refs/heads/uat'
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Deploy to CloudHub2 - UAT
        run: |
          mvn deploy -DskipTests -DmuleDeploy --settings .maven/settings.xml \
            -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
            -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
            -Danypoint.platform.client_id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
            -Danypoint.platform.client_secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
            -DcloudhubEnvironment=uat \
            -Dtarget=UAT_TARGET \
            -Denv=uat

  deploy-to-prd:
    name: Deploy to PROD
    needs: publish-to-exchange
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Deploy to CloudHub2 - PROD
        run: |
          mvn deploy -DskipTests -DmuleDeploy --settings .maven/settings.xml \
            -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
            -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
            -Danypoint.platform.client_id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
            -Danypoint.platform.client_secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
            -DcloudhubEnvironment=prod \
            -Dtarget=PROD_TARGET \
            -Denv=prod
